apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-resume-ingress
  namespace: ai-resume
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: resume.deriou.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ai-resume-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-resume-web
                port:
                  number: 80
