apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-resume-quota
  namespace: ai-resume
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 1536Mi
    pods: "8"
