apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-resume-uploads-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/ai-resume/uploads
    type: DirectoryOrCreate
  claimRef:
    namespace: ai-resume
    name: ai-resume-uploads-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-resume-uploads-pvc
  namespace: ai-resume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: ai-resume-uploads-pv
